services:
  books:
    container_name: sankirtanam
    build: .
    restart: always
    ports:
      - "3108:3108"
    volumes:
      - ./data:/data/books
    environment:
      - BOOKS_DATA_DIR=/data/books
      - BOOKS_WARM_LANGS=eng,rus
      - SITE_URL=https://sankirtan.am
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
